name: Update README

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3

      - name: Generate README
        uses: muesli/readme-scribe@d2f6ab32d6b9f5b59941fe782d6c7e6499a37fe4 # pin@master
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # pin@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
